# fly.toml app configuration file generated for shelf-schema on 2023-08-22T20:37:42-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shelf-schema"
primary_region = "ord"

[build]

[env]
  PORT = "4000" 

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
